=== Nuri0/qual-o-mat-data/schema/overview.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Election overview",
  "description": "Overview and info of an election",
  "type": "object",
  "properties": {
    "title": {
      "description": "Election name",
      "type": "string"
    },
    "date": {
      "description": "Date the election held place on",
      "type": "string",
      "format": "date"
    },
    "info": {
      "description": "URL to the Wikipedia page of the election",
      "type": "string",
      "format": "uri"
    },
    "slug": {
      "description": "Context path / slug of the original Wahl-o-Mat",
      "type": "string",
      "format": "uri"
    },
    "data_source": {
      "description": "URL to the source of the election data",
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["title", "date", "info", "slug", "data_source"]
}

=== Nuri0/qual-o-mat-data/data/2021/mecklenburgvorpommern/overview.json
{
  "title":"Landtagswahl Mecklenburg-Vorpommern",
  "date":"2021-09-26",
  "info":"https://de.wikipedia.org/wiki/Landtagswahl_in_Mecklenburg-Vorpommern_2021",
  "slug":"mecklenburgvorpommern2021",
  "data_source":"https://www.wahl-o-mat.de/mecklenburgvorpommern2021/PositionsVergleichMecklenburgVorpommern2021.pdf"
}

=== Nuri0/qual-o-mat-data/data/2022/nordrheinwestfalen/overview.json
{
  "title":"Landtagswahl Nordrhein-Westfalen",
  "date":"2022-05-15",
  "info":"https://de.wikipedia.org/wiki/Landtagswahl_in_Nordrhein-Westfalen_2022",
  "slug":"nordrheinwestfalen2022",
  "data_source":"https://www.wahl-o-mat.de/nordrheinwestfalen2022/PositionsVergleichNordrheinWestfalen2022.pdf"
}
